

# not sure if these have to be different to mine
server.port=8787
#spring.cloud.function.definition=process
spring.cloud.stream.bindings.process-in-0.destination=jobAddedToMachines
#spring.cloud.stream.kafka.binder.brokers=localhost:9092
#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=500
#
#windowstore.name=scheduling-windowstore
#window.size.ms=30000

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.cloud.stream.bindings.jobAddedToMachineChannel.destination=addJobToMachines

#spring.kafka.bootstrap-servers=localhost:9092


