spring.main.web-application-type=reactive

langchain4j.google-ai-gemini.chat-model.api-key=AIzaSyDhbNvoeT5Rh2dCjxvJTfeNOIm9U2ZTQHg
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash
#langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash-lite
langchain4j.google-ai-gemini.chat-model.strict-tools=true
langchain4j.google-ai-gemini.chat-model.temperature=0.0
langchain4j.google-ai-gemini.chat-model.timeout=PT60S
langchain4j.google-ai-gemini.chat-model.log-requests=false
langchain4j.google-ai-gemini.chat-model.log-responses=false
logging.level.dev.langchain4j=DEBUG