server.port=8084

spring.datasource.url=jdbc:h2:file:./data/maintenance-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

langchain4j.google-ai-gemini.chat-model.api-key={PUT YOUR GEMINI KEY HERE}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash
#langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash-lite
langchain4j.google-ai-gemini.chat-model.strict-tools=true
langchain4j.google-ai-gemini.chat-model.temperature=0.0
langchain4j.google-ai-gemini.chat-model.timeout=PT60S
langchain4j.google-ai-gemini.chat-model.log-requests=false
langchain4j.google-ai-gemini.chat-model.log-responses=false
logging.level.dev.langchain4j=DEBUG