# Kafka StreamBridge configuration
spring.cloud.stream.bindings.timesheetEvent-out-0.destination=timesheet-events
spring.cloud.stream.bindings.shiftPublished-out-0.destination=shift-published-events

# Kafka binder configuration
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.defaultBrokerPort=9092


spring.cloud.stream.defaultBinder=kafka

