server.port=8787
spring.cloud.function.definition=process
spring.cloud.stream.bindings.process-in-0.destination=jobAddedToMachines
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=500
spring.jackson.serialization.indent_output=true

# A unique ID for this application
spring.cloud.stream.kafka.streams.binder.application-id=business

# The shared parent directory for all state stores
spring.cloud.stream.kafka.streams.binder.configuration.state.dir=C:/kafka-streams-state

windowstore.name=scheduling-windowstore
window.size.ms=30000

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.cloud.stream.bindings.machineScheduledChannel.destination=machineSchedulings
spring.cloud.stream.bindings.jobAddedToMachineChannel.destination=jobAddedToMachines
#spring.cloud.stream.bindings.machineScheduleUpdatedChannel.destination=cargoroutings

#spring.kafka.bootstrap-servers=localhost:9092

langchain4j.google-ai-gemini.chat-model.api-key={your gemini api key here}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash
#langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.0-flash-lite
langchain4j.google-ai-gemini.chat-model.strict-tools=true
langchain4j.google-ai-gemini.chat-model.temperature=0.0
langchain4j.google-ai-gemini.chat-model.timeout=PT60S
langchain4j.google-ai-gemini.chat-model.log-requests=false
langchain4j.google-ai-gemini.chat-model.log-responses=false
logging.level.dev.langchain4j=DEBUG
