server.port=8080

spring.cloud.function.definition=process
spring.cloud.stream.bindings.process-in-0.destination=materialsConsumed
spring.cloud.stream.bindings.process-in-0.content-type=application/json
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=500
spring.cloud.stream.kafka.streams.binder.configuration.application.server: my-host-2:8080

spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.indent_output=true
logging.level.org.springframework.kafka=INFO
logging.level.com.example=DEBUG

windowstore.name=inventory-windowstore
window.size.ms=30000
