server.port=8081

# Explicitly define the single function you want to use for event processing.
spring.cloud.function.definition=receiveNewJobEvent

# Explicitly mark other functional beans as ineligible for binding.
spring.cloud.function.ineligible-definitions=handleMaterialAllocation,sendToDlqAndContinue

# Configure the binding for your event handler.
spring.cloud.stream.bindings.receiveNewJobEvent-in-0.destination=jobAddedToMachines
spring.cloud.stream.bindings.receiveNewJobEvent-in-0.group=material-allocation-group


spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=500

spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.indent_output=true
logging.level.org.springframework.kafka=INFO
logging.level.com.example=DEBUG

windowstore.name=inventory-windowstore
window.size.ms=30000
